language: node_js

node_js:
  - '4'

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test

notifications:
  email: false
  slack:
    secure: kS+qBOmpImnPkfpk2wDr1AX8fNnkd7Ond44mB6CrQ724US8scuAJ1aK+44noQloKmu1U0ezQvT0OYwBpqCkI7EMouF7kHUryJSmni9sASQ9chALc/88qv8K8IZlNF2rk5rDWoFkrnWY+rJ/gCsuUqqRdw5FQYFPtjPZhqOX5XtiptzZsidOxXs4k9LeO3eToQsSvoWHH1/cwOfmB9b+BzG3iror4qLn5SaVmIDBHeBYV3Y6z3kMtUvUSPiizkFaQ5PqfWzh0rrX9trcpiJm0RYc5mb/R51hC6BSBsgbbgIWtaEo/iLi6LpTeH3U1Z4jXmrcWCbI0RnpOvqr35pXfyGrf7v06I05R1hZg1CvVVQeG8TLZtzX8r68LEk4k4gvDLq+X3AMiWyy9vxXmwtnciPWvRTSkw4Az4kWokcplIh9rVyIEW3KTi3+CwUwUXf0+L+wH0vWgjDaFXLWvhIqe93JKkVZjNVuvOsDjm49/HM0q9M2SDQLcZrv3rD0cd4oNalIkm8zbWKHKesANF5QQu8G9B1s5Sm65JXCgXy4suzMEVsLiwx3MP9Dlh6Squ+Vbg8gxmvGpa63YbxV8de3D9d+uW1CXLUL++PYlwhlHr5ANpJCRTBGVzb+vKWY13EVUpa7+N4D1q3R6PF3RccrdKQkRFXX3jFO7YxMu00M678M=
